### ISSUE TITLE
Tests failed

### ISSUE THREAD

**Issue by petrixs** [aerospike/aerospike-loader#2]
```
ERROR AsWriterTask     :228  - File:data.csv Line:2 Integer/Long Parse Error:java.lang.NumberFormatException: For input string: "key1"
ERROR AsWriterTask     :228  - File:data.csv Line:3 Integer/Long Parse Error:java.lang.NumberFormatException: For input string: "key2"
ERROR AsWriterTask     :228  - File:data.csv Line:5 Integer/Long Parse Error:java.lang.NumberFormatException: For input string: "key4"
ERROR AsWriterTask     :228  - File:data.csv Line:4 Integer/Long Parse Error:java.lang.NumberFormatException: For input string: "key3"
ERROR AsWriterTask     :228  - File:data.csv Line:6 Integer/Long Parse Error:java.lang.NumberFormatException: For input string: "key5"
ERROR AsWriterTask     :228  - File:data.csv Line:7 Integer/Long Parse Error:java.lang.NumberFormatException: For input string: "key6"
ERROR AsWriterTask     :228  - File:data.csv Line:8 Integer/Long Parse Error:java.lang.NumberFormatException: For input string: "key7"
INFO  AerospikeLoad    :533  - Reader completed 11-lines in 0.002sec, From file: data.csv
ERROR AsWriterTask     :228  - File:data.csv Line:11 Integer/Long Parse Error:java.lang.NumberFormatException: For input string: "key10"
ERROR AsWriterTask     :228  - File:data.csv Line:10 Integer/Long Parse Error:java.lang.NumberFormatException: For input string: "key9"
ERROR AsWriterTask     :228  - File:data.csv Line:9 Integer/Long Parse Error:java.lang.NumberFormatException: For input string: "key8"
INFO  AerospikeLoad    :426  - Reader thread pool terminated
INFO  AerospikeLoad    :430  - Shutdown down writer thread pool
INFO  AerospikeLoad    :433  - Writer thread pool terminated
INFO  AerospikeLoad    :436  - Final Statistics of importer: (Succesfull Writes = 136, Errors=0(0-Write,0-Read,0-Processing)
INFO  AerospikeLoad    :448  - Aerospike loader completed
===============
Put/Get mismatch: Expected 80. Received null.
Put/Get mismatch: Expected 93. Received null.
Put/Get mismatch: Expected 90. Received null.
Put/Get mismatch: Expected 46. Received null.
Put/Get mismatch: Expected 56. Received null.
Put/Get mismatch: Expected 97. Received null.
Put/Get mismatch: Expected 88. Received null.
Put/Get mismatch: Expected 81. Received null.
Put/Get mismatch: Expected 14. Received null.
Put/Get mismatch: Expected 23. Received null.
TestValidateBlob: start
INFO  AerospikeLoad    :96  - Aerospike loader started
INFO  AerospikeLoad    :196  - Number of data files:1
INFO  Parser           :165  - Number of columns: 2(metadata) + 1(bins)
INFO  AerospikeLoad    :207  - Config file processed.
INFO  AerospikeLoad    :403  - Parameters:[ host=127.0.0.1, port=3000, ns=test, set=null, ttl=-1, timeout=0, write-action=UPDATE, fileType=csv, delimiter=,, timeZoneOffset=0, ignoreFirstLine=true, abortErrorCount=0]
INFO  AerospikeLoad    :412  - Reader pool size : 24
INFO  PrintStat        :85  - 2015-06-11 15:36:22 load(Write count=136 tps=136 Errors=0 (Timeout:0 KeyExists:0 othersWrites:0 ReadErrors:0 Processing:0) Progress:93%
INFO  AerospikeLoad    :422  - Shutdown down reader thread pool
INFO  AerospikeLoad    :538  - Processing: data.csv
INFO  AerospikeLoad    :533  - Reader completed 11-lines in 0.001sec, From file: data.csv
INFO  AerospikeLoad    :426  - Reader thread pool terminated
INFO  AerospikeLoad    :430  - Shutdown down writer thread pool
INFO  AerospikeLoad    :433  - Writer thread pool terminated
INFO  AerospikeLoad    :436  - Final Statistics of importer: (Succesfull Writes = 146, Errors=0(0-Write,0-Read,0-Processing)
INFO  AerospikeLoad    :448  - Aerospike loader completed
Bin matched: namespace=test set=set1 key=key1 bin=loc value=loc80 generation=60 expiration=0
Bin matched: namespace=test set=set2 key=key2 bin=loc value=loc93 generation=60 expiration=0
Bin matched: namespace=test set=set3 key=key3 bin=loc value=loc90 generation=60 expiration=0
Bin matched: namespace=test set=set4 key=key4 bin=loc value=loc46 generation=60 expiration=0
Bin matched: namespace=test set=set0 key=key5 bin=loc value=loc56 generation=60 expiration=0
Bin matched: namespace=test set=set1 key=key6 bin=loc value=loc97 generation=60 expiration=0
Bin matched: namespace=test set=set2 key=key7 bin=loc value=loc88 generation=60 expiration=0
Bin matched: namespace=test set=set3 key=key8 bin=loc value=loc81 generation=60 expiration=0
Bin matched: namespace=test set=set4 key=key9 bin=loc value=loc14 generation=60 expiration=0
Bin matched: namespace=test set=set0 key=key10 bin=loc value=loc23 generation=60 expiration=0
Tests run: 8, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.455 sec <<< FAILURE! - in com.aerospike.load.CsvFileParserTest
testValidateInteger(com.aerospike.load.CsvFileParserTest)  Time elapsed: 0.034 sec  <<< FAILURE!
java.lang.AssertionError: null
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at com.aerospike.load.CsvFileParserTest.testValidateInteger(CsvFileParserTest.java:140)

testValidateBlob(com.aerospike.load.CsvFileParserTest)  Time elapsed: 0.021 sec  <<< FAILURE!
java.lang.AssertionError: null
    at org.junit.Assert.fail(Assert.java:86)
    at org.junit.Assert.assertTrue(Assert.java:41)
    at org.junit.Assert.assertTrue(Assert.java:52)
    at com.aerospike.load.CsvFileParserTest.testValidateBlob(CsvFileParserTest.java:233)


Results :

Failed tests: 
  CsvFileParserTest.testValidateInteger:140 null
  CsvFileParserTest.testValidateBlob:233 null

```

The problem in this file:
src/test/resources/integerValidation.json

Fix
{
        "version" : "1.0",
        "input_type" : "csv",
        "csv_style": { "delimiter": "," , "n_columns_datafile": 3, "ignore_first_line": true },

```
    "key": {"column_name":"key", "type": "String"},

    "set": {"column_name":"set", "type": "string"},


    "binlist": [
        {"name": "age",
            "value": {"column_position": 3, "type" : "integer"}
            }
    ]
```

}

**Comment by citrusraj** [comment]
Fixed in release 2.0
